# Generated by Django 2.2.12 on 2020-06-23 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200623_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='real_name',
            new_name='username',
        ),
    ]
