# Generated by Django 2.2.12 on 2020-06-23 16:49

import apps.accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200623_2216'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
    ]
